# Generated by Django 5.2.4 on 2025-08-01 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_turno', models.DateTimeField()),
                ('kilometraje', models.PositiveIntegerField(default=0)),
                ('observaciones_tecnicas', models.TextField(blank=True)),
                ('fecha_siguiente_servicio', models.DateField(blank=True, null=True)),
                ('kilometraje_siguiente_servicio', models.PositiveIntegerField(blank=True, null=True)),
                ('mantenimiento', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], default='preventivo', max_length=15)),
                ('agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_de_trabajo', to='agendas.agenda')),
            ],
        ),
    ]
