# Generated by Django 5.2.4 on 2025-07-28 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('kilometraje', models.PositiveIntegerField(default=0)),
                ('fecha_siguiente_servicio', models.DateField(blank=True, null=True)),
                ('kilometraje_siguiente_servicio', models.PositiveIntegerField(blank=True, null=True)),
                ('observaciones_tecnicas', models.TextField(blank=True)),
                ('fecha_turno', models.DateField()),
                ('cliente', models.CharField(max_length=50, null=True)),
                ('mantenimiento', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], default='preventivo', max_length=15)),
                ('taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orden_de_trabajo', to='talleres.taller')),
            ],
        ),
    ]
