# Generated by Django 5.2.4 on 2025-07-30 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0001_initial'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordendetrabajo',
            old_name='fecha_entrega',
            new_name='fecha_entrega_estimada',
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='agendas.agenda'),
        ),
    ]
