# Generated by Django 5.2.4 on 2025-08-01 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0001_initial'),
        ('talleres', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orden_de_trabajo', to='talleres.taller'),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='tecnico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='usuarios.administradortecnico'),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='vehiculos.vehiculo'),
        ),
    ]
