# Generated by Django 5.2.4 on 2025-07-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='cliente',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
