# Generated by Django 5.2.4 on 2025-07-30 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_rename_fecha_entrega_ordendetrabajo_fecha_entrega_estimada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='fecha_entrega_estimada',
        ),
    ]
