# Generated by Django 5.2.4 on 2025-08-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='fecha_entrega',
            field=models.DateField(null=True),
        ),
    ]
