# Generated by Django 5.2.4 on 2025-08-01 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0001_initial'),
        ('ordenes', '0003_ordendetrabajo_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='agendas.agenda'),
        ),
    ]
