# Generated by Django 5.2.4 on 2025-08-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_alter_ordendetrabajo_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
