# Generated by Django 5.2.4 on 2025-08-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_alter_ordendetrabajo_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='observaciones_tecnicas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
