# Generated by Django 5.2.4 on 2025-08-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_alter_ordendetrabajo_observaciones_tecnicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='kilometraje',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
