# Generated by Django 5.2.4 on 2025-07-30 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.BooleanField(default=True)),
                ('martes', models.BooleanField(default=True)),
                ('miercoles', models.BooleanField(default=True)),
                ('jueves', models.BooleanField(default=True)),
                ('viernes', models.BooleanField(default=True)),
                ('sabado', models.BooleanField(default=False)),
                ('domingo', models.BooleanField(default=False)),
                ('horario_desde', models.TimeField()),
                ('horario_hasta', models.TimeField()),
                ('turnos_maximos_por_hora', models.PositiveIntegerField(default=1)),
                ('taller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='talleres.taller')),
            ],
        ),
    ]
