# Generated by Django 5.2.4 on 2025-07-28 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talleres', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisodeacceso',
            name='vehiculo_autorizado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehiculos.vehiculo'),
        ),
        migrations.AddField(
            model_name='administradortecnico',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.taller'),
        ),
        migrations.AddField(
            model_name='permisodeacceso',
            name='autoriza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permiso_que_orotgo', to='usuarios.cliente'),
        ),
    ]
