# Generated by Django 5.2.4 on 2025-07-28 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisodeacceso',
            name='autoriza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permiso_que_otorgo', to='usuarios.cliente'),
        ),
    ]
