# Generated by Django 5.2.4 on 2025-07-31 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0001_initial'),
        ('usuarios', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisodeacceso',
            name='autoriza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permisos_que_otorgo', to='usuarios.cliente'),
        ),
        migrations.AlterField(
            model_name='permisodeacceso',
            name='cliente_autorizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permisos_que_recibi', to='usuarios.cliente'),
        ),
        migrations.AlterField(
            model_name='permisodeacceso',
            name='taller_autorizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permisos_de_acceso', to='talleres.taller'),
        ),
    ]
