# Generated by Django 5.2.4 on 2025-07-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='intervalo_servicio_tiempo',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='intervalo_servicio_meses',
            field=models.IntegerField(default=12),
        ),
    ]
